# Dockerfile to build the BACKEND image

#----- STAGE 1
FROM oven/bun:1-alpine AS base
WORKDIR /app
EXPOSE 8080

#----- STAGE 2
# BUILDER, installs dependencies and builds projects for production
FROM base AS builder
WORKDIR /app
COPY package.json bun.lock ./
COPY apps/frontend/package.json ./apps/frontend/
COPY apps/backend-nest/. ./apps/backend-nest
COPY packages/shared/ ./packages/shared
RUN bun install --frozen-lockfile

# Build shared types first, then backend
RUN bun run build:shared
WORKDIR /app/apps/backend-nest
RUN bun run build

#----- STAGE 3
# PRODUCTION, finalizes the production build
FROM node:23.6-alpine AS production
WORKDIR /app

ENV NODE_ENV=production

# 1. Setup non-root user
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodejs -u 1001 -G nodejs

USER nodejs

COPY --from=builder --chown=nodejs:nodejs /app/node_modules /app/node_modules

COPY --from=builder --chown=nodejs:nodejs /app/package.json ./package.json
COPY --from=builder --chown=nodejs:nodejs /app/bun.lock ./bun.lock

# Copy the built backend-nest code and its package file to the workspace folder
COPY --from=builder --chown=nodejs:nodejs /app/apps/backend-nest /app/apps/backend-nest
# Copy built shared types (workspace dependency)
COPY --from=builder --chown=nodejs:nodejs /app/packages/shared /app/packages/shared

CMD ["node", "apps/backend-nest/dist/main.js"]
