
# Dockerfile to build the BACKEND image

#----- STAGE 1
FROM node:23.6-alpine AS base
WORKDIR /app

# This is root package with workspaces, 
# hence the Docker workdir structure /app/backend-nest
COPY package*.json ./
EXPOSE 8080

#----- STAGE 2
# BUIDLER, installs dependencies and builds projects for production
FROM base AS builder
WORKDIR /app
COPY backend-nest/. ./backend-nest
COPY shared/ ./shared
RUN npm install

# Build shared types first, then backend
RUN npm run build:shared
WORKDIR /app/backend-nest
RUN npm run build

#----- STAGE 3
# PRODUCTION, finalizes the production build
FROM base AS production
WORKDIR /app 

ENV NODE_ENV=production

# 1. Setup non-root user
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodejs -u 1001 -G nodejs

USER nodejs

COPY --from=builder --chown=nodejs:nodejs /app/node_modules /app/node_modules

COPY --from=builder --chown=nodejs:nodejs /app/package.json ./package.json
COPY --from=builder --chown=nodejs:nodejs /app/package-lock.json ./package-lock.json

# Copy the built backend-nest code and its package file to the workspace folder
COPY --from=builder --chown=nodejs:nodejs /app/backend-nest /app/backend-nest
# Copy built shared types (workspace dependency)
COPY --from=builder --chown=nodejs:nodejs /app/shared /app/shared

CMD ["npm", "run", "docker:start:prod"] 